// Embeds the OpenAPI spec into a TS module so it can be served from a
// superadmin-gated route (and bundled reliably into the standalone build,
// without depending on filesystem access at runtime). Runs on prebuild/predev.
import { readFile, writeFile, access } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "openapi.yaml");
const dest = join(root, "lib", "openapiSpec.ts");

try {
  await access(src);
} catch {
  console.warn("[embed-openapi] openapi.yaml not found; skipping.");
  process.exit(0);
}

const yaml = await readFile(src, "utf8");
const out =
  "// AUTO-GENERATED by scripts/embed-openapi.mjs — do not edit by hand.\n" +
  `export const OPENAPI_SPEC = ${JSON.stringify(yaml)};\n`;
await writeFile(dest, out);
console.log("[embed-openapi] wrote lib/openapiSpec.ts");
